sources:
  # --- International ---
  - name: "CNBC Top News"
    url: "https://www.cnbc.com/id/100003114/device/rss/rss.html"

  - name: "Yahoo Finance"
    url: "https://finance.yahoo.com/rss/topstories"

  - name: "MarketWatch"
    url: "https://feeds.marketwatch.com/marketwatch/topstories/"

  - name: "CoinDesk"
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/"

  # --- Russia (ONLY ONE) ---
  - name: "РБК (full)"
    url: "https://rssexport.rbc.ru/rbcnews/news/30/full.rss"
